[tool.poetry]
name = "botx-fsm"
version = "0.1.7"
description = "FSM middleware for using with pybotx"
authors = ["Nik Sidnev <sidnev.nick@gmail.com>"]


[tool.poetry.dependencies]
python = ">=3.7, <3.10"
botx = ">=0.17.0, <0.28.1"
aioredis = "^1.3.1"
async_lru = "^1.0.2"
cachetools = "^4.2.2"
molten = "^1.0.2"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
isort = "^4.3"
autoflake = "^1.3"
mypy = "^0.931"
flake8-fixme = "^1.1"
wemake-python-styleguide = "^0.15.0"
pytest = "~5.4.1"
pytest-asyncio = "^0.15.0"
pytest-cov = "^2.8.1"
starlette = "^0.16.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
