# https://python-poetry.org/docs/

[tool.poetry]
name = "pybotx-fsm"
version = "0.3.7"
description = "FSM middleware for using with pybotx"
readme = "README.md"
authors = []

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
pybotx = ">=0.32.0,<0.40.0"

[tool.poetry.dev-dependencies]
add-trailing-comma = "2.2.1"
autoflake = "1.4.0"
black = "22.3.0"
isort = "5.10.1"
mypy = "0.910.0"
wemake-python-styleguide = "0.16.1"

pytest = "^6.2.5"
pytest-asyncio = "0.18.1"

[build-system]
requires = ["poetry>=1.1.12"]
build-backend = "poetry.masonry.api"
